### ISSUE TITLE
Documentation required + Error

### ISSUE THREAD

**Issue by thehamzan6** [hikmat30ce/vitalsourcePrint#2]
Hi, thank you for posting your code on github.

I tried running it, however I ran into this problem:

```
C:\Users\Hamzan Martinez\Downloads\vitalsourcePrint-master>python printbook --course 9783110416848 --email EMAIL --password PASSWORD --title Signals_And_Systems --total_pages 267
Traceback (most recent call last):
  File "printbook", line 107, in <module>
    open_url(args.email, args.password, list_url_pages, args.title, length, width, args.initial_page)
  File "printbook", line 81, in open_url
    driver = webdriver.Chrome(chrome_options=option)
  File "C:\Users\Hamzan Martinez\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\Hamzan Martinez\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Hamzan Martinez\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Hamzan Martinez\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Hamzan Martinez\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
```

Please add a proper documentation. Which python version is required?

Thank you.

**Comment by hikmat30ce** [comment]
documentation added.
error fixed

last commit [here](https://github.com/hikmat30ce/vitalsourcePrint/commit/19635c0e726c6b81fef4ed73b826405076337029)

**Comment by sal2k3** [comment]
hi hikmat,

thanks for the script. i have a question regarding clearing cache and cookie for this script / drive as it is asking to verify not robo with image verifcation  once exceed more than 100 pages while taking snaphsot.

thank you
